// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import DiscordableController from "./discordable_controller"
application.register("discordable", DiscordableController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ManagerController from "./manager_controller"
application.register("manager", ManagerController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import PhotoController from "./photo_controller"
application.register("photo", PhotoController)

import PostCategoryController from "./post_category_controller"
application.register("post-category", PostCategoryController)
