// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BadgeController from "./badge_controller"
application.register("badge", BadgeController)

import BugController from "./bug_controller"
application.register("bug", BugController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import DiscordableController from "./discordable_controller"
application.register("discordable", DiscordableController)

import EventTypeController from "./event_type_controller"
application.register("event-type", EventTypeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ManagerController from "./manager_controller"
application.register("manager", ManagerController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import PhotoController from "./photo_controller"
application.register("photo", PhotoController)

import PostCategoryController from "./post_category_controller"
application.register("post-category", PostCategoryController)

import UploadController from "./upload_controller"
application.register("upload", UploadController)
